/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainWindow.java
 *
 * Created on 08/09/2010, 15:20:34
 */

package Interface;

import javax.swing.UIManager;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import main.Main;
import main.ParametersConfig;
import main.ParametersSerial;

/**
 *
 * @author victor
 */
public class MainWindow extends javax.swing.JFrame {

    /** Creates new form MainWindow */
    public MainWindow() {
        initComponents();
        program = new Main();
        programConfig = program.getConfig();
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane = new javax.swing.JDesktopPane();
        jInternalFrameStatus = new javax.swing.JInternalFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaLog = new javax.swing.JTextArea();
        jLabelTime = new javax.swing.JLabel();
        jLabelCyclesStatus = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabelReport = new javax.swing.JLabel();
        jTextFieldTime = new javax.swing.JTextField();
        jTextFieldCycles = new javax.swing.JTextField();
        jTextFieldLength = new javax.swing.JTextField();
        jInternalFrameConfig = new javax.swing.JInternalFrame();
        jLabelStepperSpeed = new javax.swing.JLabel();
        jSpinnerStepperSpeed = new javax.swing.JSpinner();
        jLabelWireStep = new javax.swing.JLabel();
        jSpinnerWireStep = new javax.swing.JSpinner();
        jLabelStrain = new javax.swing.JLabel();
        jSpinnerStraining = new javax.swing.JSpinner();
        jLabelcycles = new javax.swing.JLabel();
        jSpinnerCycles = new javax.swing.JSpinner();
        jPanel1 = new javax.swing.JPanel();
        jToolBarOperation = new javax.swing.JToolBar();
        jButtonStart = new javax.swing.JButton();
        jButtonRestart = new javax.swing.JButton();
        jToolBarDevice = new javax.swing.JToolBar();
        jButtonConnect = new javax.swing.JButton();
        jButtonConfigSerial = new javax.swing.JButton();
        jButtonDebug = new javax.swing.JButton();
        jButtonConfigDebug = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuFile = new javax.swing.JMenu();
        jMenuItemExit = new javax.swing.JMenuItem();
        jMenuView = new javax.swing.JMenu();
        jCheckBoxMenuItemOperation = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItemStatus = new javax.swing.JCheckBoxMenuItem();
        jMenuToolBars = new javax.swing.JMenu();
        jCheckBoxMenuItemOperationToolBar = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItemDeviceTool = new javax.swing.JCheckBoxMenuItem();
        jMenuOperation = new javax.swing.JMenu();
        jMenuItemStart = new javax.swing.JMenuItem();
        jMenuItemPause = new javax.swing.JMenuItem();
        jMenuItemRestart = new javax.swing.JMenuItem();
        jMenuDevice = new javax.swing.JMenu();
        jMenuItemConnect = new javax.swing.JMenuItem();
        jMenuItemConnectDebug = new javax.swing.JMenuItem();
        jMenuConfiguration = new javax.swing.JMenu();
        jMenuItemOptions = new javax.swing.JMenuItem();
        jMenuItemSerialConfiguration0 = new javax.swing.JMenuItem();
        jMenuItemSerialConfiguration1 = new javax.swing.JMenuItem();
        jMenuHelp = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Traktana - Centro Brasileiro de Pesquisas Físicas");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jInternalFrameStatus.setClosable(true);
        jInternalFrameStatus.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        jInternalFrameStatus.setIconifiable(true);
        jInternalFrameStatus.setResizable(true);
        jInternalFrameStatus.setTitle("Status");
        jInternalFrameStatus.setFrameIcon(null);
        jInternalFrameStatus.setVisible(true);

        jTextAreaLog.setColumns(20);
        jTextAreaLog.setRows(5);
        jTextAreaLog.setText("\n LogProcess");
        jScrollPane1.setViewportView(jTextAreaLog);

        jLabelTime.setText("Time:");

        jLabelCyclesStatus.setText("Cycles:");

        jLabel1.setText("Length plain:");

        jLabelReport.setText("Report:");

        jTextFieldTime.setEditable(false);
        jTextFieldTime.setEnabled(false);

        jTextFieldCycles.setEditable(false);
        jTextFieldCycles.setEnabled(false);

        jTextFieldLength.setEditable(false);
        jTextFieldLength.setEnabled(false);

        javax.swing.GroupLayout jInternalFrameStatusLayout = new javax.swing.GroupLayout(jInternalFrameStatus.getContentPane());
        jInternalFrameStatus.getContentPane().setLayout(jInternalFrameStatusLayout);
        jInternalFrameStatusLayout.setHorizontalGroup(
            jInternalFrameStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrameStatusLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrameStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrameStatusLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrameStatusLayout.createSequentialGroup()
                        .addGroup(jInternalFrameStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelTime)
                            .addComponent(jLabelCyclesStatus))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jInternalFrameStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldLength)
                    .addComponent(jTextFieldTime, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                    .addComponent(jTextFieldCycles))
                .addContainerGap(92, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE)
            .addGroup(jInternalFrameStatusLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelReport)
                .addContainerGap(251, Short.MAX_VALUE))
        );
        jInternalFrameStatusLayout.setVerticalGroup(
            jInternalFrameStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrameStatusLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrameStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTime))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jInternalFrameStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCyclesStatus)
                    .addComponent(jTextFieldCycles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jInternalFrameStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldLength, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(28, 28, 28)
                .addComponent(jLabelReport)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE))
        );

        jInternalFrameStatus.setBounds(300, 20, 320, 330);
        jDesktopPane.add(jInternalFrameStatus, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jInternalFrameConfig.setClosable(true);
        jInternalFrameConfig.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        jInternalFrameConfig.setIconifiable(true);
        jInternalFrameConfig.setResizable(true);
        jInternalFrameConfig.setTitle("Operation");
        jInternalFrameConfig.setFrameIcon(null);
        jInternalFrameConfig.setVisible(true);

        jLabelStepperSpeed.setText("Stepper Speed:");

        jLabelWireStep.setText("Wire step:");

        jLabelStrain.setText("Straining:");

        jLabelcycles.setText("Cycles:");

        javax.swing.GroupLayout jInternalFrameConfigLayout = new javax.swing.GroupLayout(jInternalFrameConfig.getContentPane());
        jInternalFrameConfig.getContentPane().setLayout(jInternalFrameConfigLayout);
        jInternalFrameConfigLayout.setHorizontalGroup(
            jInternalFrameConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrameConfigLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrameConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelWireStep)
                    .addComponent(jLabelStepperSpeed)
                    .addComponent(jLabelStrain)
                    .addComponent(jLabelcycles))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jInternalFrameConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSpinnerStepperSpeed, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                    .addComponent(jSpinnerWireStep)
                    .addComponent(jSpinnerStraining)
                    .addComponent(jSpinnerCycles))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jInternalFrameConfigLayout.setVerticalGroup(
            jInternalFrameConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrameConfigLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrameConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinnerStepperSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelStepperSpeed))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jInternalFrameConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelWireStep)
                    .addComponent(jSpinnerWireStep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jInternalFrameConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinnerStraining, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelStrain))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jInternalFrameConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinnerCycles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelcycles))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jInternalFrameConfig.setBounds(30, 20, 260, 204);
        jDesktopPane.add(jInternalFrameConfig, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButtonStart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/icons/play.png"))); // NOI18N
        jButtonStart.setToolTipText("Start/Pause the process.");
        jButtonStart.setFocusable(false);
        jButtonStart.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonStart.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStartActionPerformed(evt);
            }
        });
        jToolBarOperation.add(jButtonStart);

        jButtonRestart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/icons/refresh_32.png"))); // NOI18N
        jButtonRestart.setToolTipText("Restart the process.");
        jButtonRestart.setFocusable(false);
        jButtonRestart.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonRestart.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBarOperation.add(jButtonRestart);

        jToolBarDevice.setRollover(true);

        jButtonConnect.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/icons/connect.png"))); // NOI18N
        jButtonConnect.setToolTipText("Connect device");
        jButtonConnect.setFocusable(false);
        jButtonConnect.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonConnect.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonConnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConnectActionPerformed(evt);
            }
        });
        jToolBarDevice.add(jButtonConnect);

        jButtonConfigSerial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/icons/cog.png"))); // NOI18N
        jButtonConfigSerial.setToolTipText("Serial device configuration");
        jButtonConfigSerial.setFocusable(false);
        jButtonConfigSerial.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonConfigSerial.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBarDevice.add(jButtonConfigSerial);

        jButtonDebug.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/icons/bug_add.png"))); // NOI18N
        jButtonDebug.setToolTipText("Connect serial debug");
        jButtonDebug.setFocusable(false);
        jButtonDebug.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonDebug.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBarDevice.add(jButtonDebug);

        jButtonConfigDebug.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/icons/bug_edit.png"))); // NOI18N
        jButtonConfigDebug.setToolTipText("Serial debug configuration");
        jButtonConfigDebug.setFocusable(false);
        jButtonConfigDebug.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonConfigDebug.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBarDevice.add(jButtonConfigDebug);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jToolBarOperation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToolBarDevice, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(459, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToolBarDevice, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jToolBarOperation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jMenuFile.setText("File");

        jMenuItemExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        jMenuItemExit.setText("Exit");
        jMenuItemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemExitActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemExit);

        jMenuBar1.add(jMenuFile);

        jMenuView.setText("View");

        jCheckBoxMenuItemOperation.setSelected(true);
        jCheckBoxMenuItemOperation.setText("Operation");
        jCheckBoxMenuItemOperation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItemOperationActionPerformed(evt);
            }
        });
        jMenuView.add(jCheckBoxMenuItemOperation);

        jCheckBoxMenuItemStatus.setSelected(true);
        jCheckBoxMenuItemStatus.setText("Status");
        jCheckBoxMenuItemStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItemStatusActionPerformed(evt);
            }
        });
        jMenuView.add(jCheckBoxMenuItemStatus);

        jMenuToolBars.setText("ToolBars");

        jCheckBoxMenuItemOperationToolBar.setSelected(true);
        jCheckBoxMenuItemOperationToolBar.setText("Operation");
        jMenuToolBars.add(jCheckBoxMenuItemOperationToolBar);

        jCheckBoxMenuItemDeviceTool.setSelected(true);
        jCheckBoxMenuItemDeviceTool.setText("Device/Configuration");
        jMenuToolBars.add(jCheckBoxMenuItemDeviceTool);

        jMenuView.add(jMenuToolBars);

        jMenuBar1.add(jMenuView);

        jMenuOperation.setText("Operation");

        jMenuItemStart.setText("Start");
        jMenuOperation.add(jMenuItemStart);

        jMenuItemPause.setText("Pause");
        jMenuItemPause.setEnabled(false);
        jMenuOperation.add(jMenuItemPause);

        jMenuItemRestart.setText("Restart");
        jMenuOperation.add(jMenuItemRestart);

        jMenuBar1.add(jMenuOperation);

        jMenuDevice.setText("Device");

        jMenuItemConnect.setText("Connect");
        jMenuDevice.add(jMenuItemConnect);

        jMenuItemConnectDebug.setText("Connect Debug");
        jMenuDevice.add(jMenuItemConnectDebug);

        jMenuBar1.add(jMenuDevice);

        jMenuConfiguration.setText("Configuration");

        jMenuItemOptions.setText("Options");
        jMenuConfiguration.add(jMenuItemOptions);

        jMenuItemSerialConfiguration0.setText("Serial Configuration 0");
        jMenuItemSerialConfiguration0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSerialConfiguration0ActionPerformed(evt);
            }
        });
        jMenuConfiguration.add(jMenuItemSerialConfiguration0);

        jMenuItemSerialConfiguration1.setText("Serial Configuration 1");
        jMenuItemSerialConfiguration1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSerialConfiguration1ActionPerformed(evt);
            }
        });
        jMenuConfiguration.add(jMenuItemSerialConfiguration1);

        jMenuBar1.add(jMenuConfiguration);

        jMenuHelp.setText("Help");
        jMenuBar1.add(jMenuHelp);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jDesktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 804, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDesktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 622, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItemExitActionPerformed

    private void jMenuItemSerialConfiguration0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSerialConfiguration0ActionPerformed
        // TODO add your handling code here:
        ConfigSerialDialog cfgframe0 = new ConfigSerialDialog(this, true);
        cfgframe0.setTitle("Serial Configuration 0");
        cfgframe0.setConfig(programConfig.getSerialconfig0());
        cfgframe0.setVisible(true);
    }//GEN-LAST:event_jMenuItemSerialConfiguration0ActionPerformed

    private void jMenuItemSerialConfiguration1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSerialConfiguration1ActionPerformed
        // TODO add your handling code here:
        ConfigSerialDialog cfgframe1 = new ConfigSerialDialog(this, true);
        cfgframe1.setTitle("Serial Configuration 1");
        cfgframe1.setConfig(programConfig.getSerialconfig1());
        cfgframe1.setVisible(true);
    }//GEN-LAST:event_jMenuItemSerialConfiguration1ActionPerformed

    private void jButtonStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStartActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButtonStartActionPerformed

    private void jCheckBoxMenuItemOperationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItemOperationActionPerformed
        // TODO add your handling code here:
        if(jCheckBoxMenuItemOperation.getState()){
            jInternalFrameConfig.setVisible(true);
        }else{
            jInternalFrameConfig.setVisible(false);
        }
    }//GEN-LAST:event_jCheckBoxMenuItemOperationActionPerformed

    private void jCheckBoxMenuItemStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItemStatusActionPerformed
        // TODO add your handling code here:
        if(jCheckBoxMenuItemStatus.getState()){
            jInternalFrameStatus.setVisible(true);
        }else{
            jInternalFrameStatus.setVisible(false);
        }
    }//GEN-LAST:event_jCheckBoxMenuItemStatusActionPerformed

    private void jButtonConnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConnectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonConnectActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                     UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                } catch (UnsupportedLookAndFeelException ex) {
                     ex.printStackTrace();
                } catch (IllegalAccessException ex) {
                     ex.printStackTrace();
                } catch (InstantiationException ex) {
                     ex.printStackTrace();
                } catch (ClassNotFoundException ex) {
                     ex.printStackTrace();
                }

                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonConfigDebug;
    private javax.swing.JButton jButtonConfigSerial;
    private javax.swing.JButton jButtonConnect;
    private javax.swing.JButton jButtonDebug;
    private javax.swing.JButton jButtonRestart;
    private javax.swing.JButton jButtonStart;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItemDeviceTool;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItemOperation;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItemOperationToolBar;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItemStatus;
    private javax.swing.JDesktopPane jDesktopPane;
    private javax.swing.JInternalFrame jInternalFrameConfig;
    private javax.swing.JInternalFrame jInternalFrameStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelCyclesStatus;
    private javax.swing.JLabel jLabelReport;
    private javax.swing.JLabel jLabelStepperSpeed;
    private javax.swing.JLabel jLabelStrain;
    private javax.swing.JLabel jLabelTime;
    private javax.swing.JLabel jLabelWireStep;
    private javax.swing.JLabel jLabelcycles;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuConfiguration;
    private javax.swing.JMenu jMenuDevice;
    private javax.swing.JMenu jMenuFile;
    private javax.swing.JMenu jMenuHelp;
    private javax.swing.JMenuItem jMenuItemConnect;
    private javax.swing.JMenuItem jMenuItemConnectDebug;
    private javax.swing.JMenuItem jMenuItemExit;
    private javax.swing.JMenuItem jMenuItemOptions;
    private javax.swing.JMenuItem jMenuItemPause;
    private javax.swing.JMenuItem jMenuItemRestart;
    private javax.swing.JMenuItem jMenuItemSerialConfiguration0;
    private javax.swing.JMenuItem jMenuItemSerialConfiguration1;
    private javax.swing.JMenuItem jMenuItemStart;
    private javax.swing.JMenu jMenuOperation;
    private javax.swing.JMenu jMenuToolBars;
    private javax.swing.JMenu jMenuView;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinnerCycles;
    private javax.swing.JSpinner jSpinnerStepperSpeed;
    private javax.swing.JSpinner jSpinnerStraining;
    private javax.swing.JSpinner jSpinnerWireStep;
    private javax.swing.JTextArea jTextAreaLog;
    private javax.swing.JTextField jTextFieldCycles;
    private javax.swing.JTextField jTextFieldLength;
    private javax.swing.JTextField jTextFieldTime;
    private javax.swing.JToolBar jToolBarDevice;
    private javax.swing.JToolBar jToolBarOperation;
    // End of variables declaration//GEN-END:variables
    private Main program;
    private ParametersConfig programConfig;
    private ParametersSerial SerialConfig;
}
